export const THEME = {
  DANGER_COLOR: "red",
  BACKGROUND_COLOR: "#6b0b6b",
  BORDER_COLOR: "#eee",
  INPUT_BOTTOM_BORDER_COLOR: "#1a237e",
  CANCEL_BUTTON_COLOR: "#757575",
  SAVE_BUTTON_COLOR: "#2e7d32",
  REMOVE_BUTTON_COLOR: "#c62828",
  EDIT_BUTTON_COLOR: "#607d8b",
};
